# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5d1c34fa305fc323524302b17bc26e16"
name = "pg-template"
handle = "pg-template"
application_url = "https://designated-designers-volkswagen-hopes.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "nodejs-pg-app.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://designated-designers-volkswagen-hopes.trycloudflare.com/auth/callback",
  "https://designated-designers-volkswagen-hopes.trycloudflare.com/auth/shopify/callback",
  "https://designated-designers-volkswagen-hopes.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
