# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "pg-template"
client_id = "5d1c34fa305fc323524302b17bc26e16"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_payment_gateways,write_payment_sessions"

[auth]
redirect_urls = [
  "https://app.example.com/api/auth/callback",
  "https://app.example.com/api/auth/oauth/callback",
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
include_config_on_deploy = true
